### ISSUE TITLE
你好, 部署到k3s后, 访问出现400

### ISSUE THREAD

**Issue by badboy-tian** [duolabmeng6/paddlehub_ppocr#4]
```
apiVersion: v1
kind: Service
metadata:
  name: paddleocr
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30038
  selector:
    app: paddleocr
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paddleocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paddleocr
  template:
    metadata:
      labels:
        app: paddleocr
    spec:
      containers:
        - image: registry.cn-hongkong.aliyuncs.com/llapi/ppocr:1.6.server
          imagePullPolicy: IfNotPresent
          name: paddleocr
          command:
            - /bin/bash
            - -c
            - "sh /PaddleOCR/start.sh"
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP

```

访问
```
{"images":["/9j/4RJwRXhpZgAATU0AKgAAAAgABwESAA.............省略一堆base64....................kc/q/7H/9k="]}
```

错误:
```
code 400, message Bad request version ('ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93JJ\x00\x00\x00\x00\x00\x15\x00\x13\x00\x00\x10parse.i7play.com\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
```
